#! /bin/bash

#Color Declarations
std=`tput setaf 15`
red=`tput setaf 9 bold`
green=`tput setaf 10 bold`
yellow=`tput setaf 11 bold`
pink=`tput setaf 57`
blue=`tput setaf 27 bold`

#Main Script
echo ""
echo ""
echo "${blue}   |||||||||||||||||||||||                    ||||||||||||${std}"
echo "${blue}  ||                     ||||||||||||              ||${std}"
echo "${blue} ||                       ||       ||      |||     ||${std}"
echo "${blue} ||                       ||       ||              ||${std}"
echo "${blue} ||                       ||       ||      |||     ||${std}"
echo "${blue}  ||                     ||||||||||||              ||${std}"
echo "${blue}   |||||||||||||||||||||||                         ||${std}"
echo "NETDRIVE-CONNECTOR by Nightstalker"
echo ""
echo ""
read -p "${green}Enter the IP of the Server: ${std}" ip_adress;

if ping -c 1 $ip_adress &> /dev/null
then
        echo ""
        echo "${blue}The Host is reachable!${std}"
        i=1
else
        i=0
fi

while [[ $i -eq 0 ]]
do
        echo "${red}The Host is not reachable! Please try a different IP!${std}"
        read -p "Enter the IP of the Server: " ip_adress;
        if ping -c 1 $ip_adress &> /dev/null
        then
                echo ""
                echo "${blue}The Host is reachable!${std}"
                i=1
        else
                i=0
        fi
done

echo ""
echo ""
read -p "${green}Enter the Sharename of the Drive: ${std}" sharename;
echo ""
echo "${blue}The Sharename is:${std}"
echo "$sharename"

echo ""
echo ""
read -p "${green}Enter the Username for the Server: ${std}" user;
echo ""
echo "${blue}The Username is:${std}"
echo "$user"

echo ""
echo ""
read -s -p "${green}Enter the Password of the User: ${std}" password;
echo ""
echo "${blue}The Password is:${std}"
echo "TOPSECRECT"

echo ""
echo ""
read -s -p "${green}Enter the absolut Path to the Mountpoint on this System: ${std}" mountpath;
echo ""
echo "${blue}Checking if the Mountpoint exists...${std}"
echo "$mountpath"

if [ -d "$mountpath" ]
then
        echo ""
        echo "${blue}The given Mountpoint already exists!${std}"
        echo "${blue}Checking if there are Files in it...${std}"

        if [ "$(ls -A $mountpath)" ]
        then
                echo ""
                echo "${red}The given Mountpath contains precious Files!${std}"
                echo "${blue}If you proceed with mounting your Netdrive there you will lose access to those Files!${std}"
                echo "${blue}You should gain access to your Files again by unmounting the Drive though.${std}"

                echo ""
                echo "${blue}Do you want to proceed?${std}"
                read -p "Yes (y)/ No (n): " n;

                while ! [[ "$n" =~ ^(y|n)$ ]];
                do
                        echo ""
                        echo "${red}Wrong Input! Please type 'y' for 'YES' or 'n' for 'NO'!${std}"
                        read -p "Yes (y)/ No (n): " n;
                done

                if [[ "$n" =~ ^(y)$ ]];
                then
                        echo ""
                        echo "${blue}Proceeding to mount the Drive!${std}"
                        echo "${blue}Mounting the Drive now...${std}"

                        if sudo mount -t cifs -o user=$user,password=$password,defaults,nofail,_netdev,file_mode=0777,dir_mode=0777 //$ip_adress/$sharename $mountpath &> /dev/null
                        then
                                echo ""
                                echo "${green}Netdrive successfully mounted!${std}"
                                echo "${green}Have fun with your Files!${std}"
                        else
                                echo ""
                                echo "${red}Netdrive could not be mounted!${std}"
                                echo "${red}Exiting the Script now!${std}"
                                exit 1
                        fi
                else
                        echo ""
                        echo "${red}Operation Aborted!${std}"
                        echo "${red}Exiting Script now!${std}"
	                      exit 1
                fi
	      else
                echo ""
                echo "${blue}Mountpath is empty!${std}"
                echo "${blue}Mounting the Drive now...${std}"

                if sudo mount -t cifs -o user=$user,password=$password,defaults,nofail,_netdev,file_mode=0777,dir_mode=0777 //$ip_adress/$sharename $mountpath &> /dev/null
                then
                        echo ""
                        echo "${green}Netdrive successfully mounted!${std}"
                        echo "${green}Have fun with your Files!${std}"
                else
                        echo ""
                        echo "${red}Netdrive could not be mounted!${std}"
                        echo "${red}Exiting the Script now!${std}"
                        exit 1
                fi
        fi
else
        echo ""
        echo "${red}The given Mountpoint doesn't exist!${std}"
        echo "${blue}Creating the Mountpoint...${std}"
        
        if sudo mkdir -p $mountpath &> /dev/null
        then
                echo ""
                echo "${blue}Mountpoint created succesfully!${std}"
                echo "${blue}Mounting the Drive now...${std}"

                if sudo mount -t cifs -o user=$user,password=$password,defaults,nofail,_netdev,file_mode=0777,dir_mode=0777 //$ip_adress/$sharename $mountpath &> /dev/null
                then
                        echo ""
                        echo "${green}Netdrive successfully mounted!${std}"
                        echo "${green}Have fun with your Files!${std}"
                else
                        echo ""
                        echo "${red}Netdrive could not be mounted!${std}"
                        echo "${red}Exiting the Script now!${std}"
                        exit 1
                fi
        else
                echo ""
                echo "${red}Mountpoint could not be created!${std}"
                echo "${red}Exiting the Script now!${std}"
                exit 1
        fi  
fi

#sudo mount -t cifs -o user=$user,password=$password,defaults,nofail,_netdev,file_mode=0777,dir_mode=0777 //$ip_adress/$sharename $mountpath
